#13 Registration new users.
horba/film-finity pull request #23
Opened 2020-06-04 22:20 UTC by IgorNazaryok

#13 Registration new users. Add  store. Methods implemented through action

2020-06-06 15:20 UTC, horba requested changes

2020-06-06 15:20 UTC, horba commented on front/src/store/modules/ReristrationUser.js
> +};
please, provide correct name for store module file
http://joxi.ru/4AkqZyjtXgwXym

by https://github.com/horba/film-finity/wiki/Frontend-Namings-and-Structure

2020-06-06 15:22 UTC, horba requested changes
please, read carefully about file namings and structure our wiki https://github.com/horba/film-finity/wiki/Frontend-Namings-and-Structure

2020-06-06 15:22 UTC, horba commented on front/src/App.vue
> +import RegForm from './components/Registration/RegForm.vue';
use `@components`

2020-06-06 15:37 UTC, horba requested changes

2020-06-06 15:37 UTC, horba commented on front/src/components/Registration/RegForm.html
> +<div class="font">
font should be setted in body in common.css

2020-06-06 15:37 UTC, horba commented on front/src/components/Registration/RegForm.css
> +  color: #292c33;
use css variables everywhere possible, please

2020-06-06 15:45 UTC, horba requested changes

2020-06-06 15:45 UTC, horba commented on front/src/components/Registration/RegForm.html
> +        <div class="accountCreate font">
account-create

2020-06-06 15:45 UTC, horba commented on front/src/components/Registration/RegForm.vue
> +<style scoped src="./RegForm.css"></style>
no shortcuts, please
we have article in wiki about ninja code. please, read it

2020-06-06 15:45 UTC, horba commented on server/Entities/Models/JobTitle.cs
> +        public ICollection<CelebrityJobTitles> CelebrityJobTitles { get; set; }
it seems we have some entities for job titles for celebrities, ask @Yaronberg about it

2020-06-06 15:45 UTC, horba commented on server/WebAPI/Controllers/CelebrityController.cs
> +
no logic in controller, please provide Service  or use existing (not repository)

2020-06-06 15:45 UTC, horba commented on server/WebAPI/Controllers/CelebrityController.cs
> +
do use automapper?

2020-06-06 19:17 UTC, horba requested changes
please, use components from css-framework
before making task check if some component already exists in element ui

https://element.eleme.io/#/en-US/component/dialog

Also, please, attach screens of implemented views to pull request description and in comment to task

2020-06-06 19:23 UTC, horba requested changes
index.js is a part of file infrastructure

2020-06-06 19:23 UTC, horba commented on front/src/components/index.js
> -export { default as HelloWorld } from './hello-world/hello-world.component.vue';
it is useful file
before deleting think why it was added
yes, hello-world were removed but it is place to export all components for shortcut import just only from `@components`

2020-06-06 19:23 UTC, horba commented on front/src/components/index.js
> -export { default as HelloWorld } from './hello-world/hello-world.component.vue';
https://www.freecodecamp.org/news/how-to-use-es6-modules-and-why-theyre-important-a9b20b480773/

2020-06-06 19:23 UTC, horba commented on front/src/components/index.js
> -export { default as HelloWorld } from './hello-world/hello-world.component.vue';
https://medium.com/groww-engineering/module-aliasing-in-webpack-f02fe1b91f94

2020-06-07 18:54 UTC, IgorNazaryok commented on server/WebAPI/Controllers/CelebrityController.cs
> +
Я не понял твои замечания по серверу. Этот код Ярослава. Что я должен сделать, исправить?

2020-06-09 12:32 UTC, closed without merging