Feature/13 Registration User
horba/film-finity pull request #28
Opened 2020-06-15 19:54 UTC by IgorNazaryok

comments on previous pull request corrected
![0](https://user-images.githubusercontent.com/57412354/84699929-1193b900-af5b-11ea-94ab-495dcb5bfa57.png)
![1](https://user-images.githubusercontent.com/57412354/84699931-122c4f80-af5b-11ea-9758-aa6c52da3c92.png)
![2](https://user-images.githubusercontent.com/57412354/84699933-12c4e600-af5b-11ea-90b2-6ac01d3c8f2a.png)
![3](https://user-images.githubusercontent.com/57412354/84699936-12c4e600-af5b-11ea-9d8c-a59fbd08cbbb.png)
![4](https://user-images.githubusercontent.com/57412354/84699938-12c4e600-af5b-11ea-8776-db0083a9285b.png)

2020-06-17 16:12 UTC, horba requested changes
1. please, read again https://github.com/horba/film-finity/wiki/JS-Code-Style-Guide and https://github.com/horba/film-finity/wiki/Frontend-Namings-and-Structure

2. also you have problems with your registration dialog structure
i propose to separate different steps into components
ff-registration-dialog - provide possibility to call dialog and manage process
his template:
```
<el-button @click="dialogVisible = true">
<el-dialog visible.sync="dialogVisible">
   <registration-form v-if="!userRegistred" @complete="userRegistred= true">
   <registration-confirmation v-if="userRegistred">
</el-dialog>
```
`complete` event in `registration-form` - custom event - read https://ru.vuejs.org/v2/guide/components-custom-events.html

3. server validation https://medium.com/better-programming/back-end-data-validations-73ea9004c6d7

4. add business logic layer - UserService in WebAPI.Services namespace

2020-06-17 16:12 UTC, horba commented on front/src/element-variables.scss
> +$--color-text-primary:  #000000 !default;
why it was red? where it was used else?

2020-06-17 16:12 UTC, horba commented on front/src/components/index.js
> +export { default as FfRegistrationUser } from './RegistrationUser/RegistrationUser.component.vue';
`'./RegistrationUser/RegistrationUser.component.vue'` -> `'./registration/registration.component.vue'`
problems:

- style of naming-files
- name of component's class and file. it is obvious that it is registration of user - it should be just registration.

2020-06-17 16:12 UTC, horba commented on front/src/components/RegistrationUser/RegistrationUser.component.html
> +      <div class="close"><el-button icon="el-icon-close" circle @click="ShowModalWindow(false)"></el-button> </div>
it is not ok that you use custom close button

2020-06-17 16:12 UTC, horba commented on front/src/components/RegistrationUser/RegistrationUser.component.css
> +}
no shortcuts
the meening word first: registration-button, email-input, password-input
actually, it is extra to specify tag in name of class

so, just .registration, .email, .login, .password

2020-06-17 16:12 UTC, horba commented on front/src/components/RegistrationUser/RegistrationUser.component.html
> +        <el-form-item class="inp-login" prop="userName">
oh, my god, you see, what i thought first when i saw class name inp - i was sure that it is class of input

please, just login 

`<el-form-item class="login" prop="userName">`

```
.login {} // or el-form-item.login {}

.login el-input {}

```

2020-06-17 16:12 UTC, horba commented on front/src/components/RegistrationUser/RegistrationUser.component.html
> +    <el-button class="second-color" @click="ShowModalWindow(true)">ВОЙТИ</el-button>
- code style of js methods - lower camelCase - showModalWindow
- function with name show can't accept boolean variable - what it means? if we pass false does it hide form?! 
- modalWindow? no, no, it is too common

possible options:
1. `<el-button class="second-color" @click="regisrationDialogVisible = true">ВОЙТИ</el-button>`
2. `<el-button class="second-color" @click="showRegisrationDialog()">ВОЙТИ</el-button>`
```
showRegistrationDialog() {
  this.regisrationDialogVisible = true;
}
```

2020-06-17 16:12 UTC, horba commented on front/src/components/RegistrationUser/RegistrationUser.component.css
> +  color: #EE4444;
css variables?

2020-06-17 16:12 UTC, horba commented on front/src/components/RegistrationUser/RegistrationUser.component.css
> +  line-height: 2.0;
are you sure? it could be problem

2020-06-17 16:12 UTC, horba commented on front/src/components/RegistrationUser/RegistrationUser.component.html
> +    :show-close="false"
again, a don't understand why you set not to show close button and then define your own one
if you need to process something on close you can use http://joxi.ru/l2Zk3XpSEPQqVA
if you need to check and cancel closing - http://joxi.ru/E2pqMzQtaLyPLA

2020-06-17 16:12 UTC, horba commented on front/src/components/RegistrationUser/RegistrationUser.component.html
> +                  @input="SetEmailExistFalse()"
naming styles
please, read again https://github.com/horba/film-finity/wiki/Frontend-Namings-and-Structure

2020-06-17 16:12 UTC, horba commented on front/src/components/RegistrationUser/RegistrationUser.component.html
> +                  @input="SetEmailExistFalse()"
also it is bad name meaning also 

`@input="emailExist = false"`

2020-06-17 16:12 UTC, horba commented on front/src/components/RegistrationUser/RegistrationUser.component.html
> +                  @input="SetEmailExistFalse()"
i can\t understand why you need it at all

2020-06-17 16:12 UTC, horba commented on front/src/components/RegistrationUser/RegistrationUser.component.html
> +            :disabled='isButton'
isButton - what it means?

2020-06-17 16:12 UTC, horba commented on front/src/components/RegistrationUser/RegistrationUser.component.html
> +      :visible.sync="isRegistrationDone"
isUserCreated ?

2020-06-17 16:12 UTC, horba commented on front/src/components/RegistrationUser/RegistrationUser.component.html
> +    <div class="close"><el-button icon="el-icon-close" circle @click="ClouseWindowRegDone()"></el-button> </div>
please, not create custom close button

2020-06-17 16:12 UTC, horba commented on front/src/components/RegistrationUser/RegistrationUser.component.html
> +    <div class="account-create">
account-creat**ed**

actually it is registration-completed-message

2020-06-17 16:12 UTC, horba commented on front/src/components/RegistrationUser/RegistrationUser.component.html
> +      <el-button type="success" icon="el-icon-check" circle></el-button>
are you sure that it should be button? theri is no actions on click - it is just icon or image

2020-06-17 16:12 UTC, horba commented on front/src/components/RegistrationUser/RegistrationUser.component.js
> +    ClouseWindowRegDone () {
all methods should be named in lower camelCase

2020-06-17 16:12 UTC, horba commented on front/src/components/RegistrationUser/RegistrationUser.component.js
> +      this.isEmailExist = false;
it is extra

2020-06-17 16:12 UTC, horba commented on front/src/components/RegistrationUser/RegistrationUser.component.vue
> +<style scoped src="./RegistrationUser.component.css"></style>
https://github.com/horba/film-finity/wiki/Frontend-Namings-and-Structure

2020-06-17 16:12 UTC, horba commented on front/src/layouts/menu/menu.layout.css
> +.buttonEnter{
doesn't it confuse you that you named in different styling your class names?

`enter-button { }` or just `button.enter {}` or `.enter {}`

2020-06-17 16:12 UTC, horba commented on front/src/layouts/menu/menu.layout.html
> +  </div>
it is strange construction at all

```
<div class="actions">    
    <el-button icon="el-icon-search" class="second-color"></el-button>
    <ff-registration-dialog/>
  </div>
```

2020-06-17 16:12 UTC, horba commented on front/src/components/RegistrationUser/RegistrationUser.component.html
> +    :visible.sync="isRegistration"
`isRegistraion `-> `registrationDialogVisible`

2020-06-17 16:12 UTC, horba commented on server/Entities/Models/Users.cs
> +        public string UserName { get; set; }
it is entity of user we don't need specify that it belongs user - just Name

2020-06-17 16:12 UTC, horba commented on server/Entities/Models/Users.cs
> +        public string UserPassword { get; set; }
it is entity of user we don't need specify that it belongs user - just Password

2020-06-17 16:12 UTC, horba commented on server/Entities/Models/Users.cs
> +    public class User
database validation https://docs.microsoft.com/en-us/ef/core/modeling/entity-properties?tabs=data-annotations%2Cwithout-nrt

2020-06-17 16:12 UTC, horba commented on server/WebAPI/Controllers/UserController.cs
> +            return BadRequest();
user interaction validation https://medium.com/better-programming/back-end-data-validations-73ea9004c6d7

2020-06-17 16:12 UTC, horba commented on server/WebAPI/Controllers/UserController.cs
> +            this.dbContext = filmFinityDbContext;
no database layer in conroller, provide UserService

2020-06-17 16:12 UTC, horba commented on server/WebAPI/Controllers/UserController.cs
> +            this.dbContext = filmFinityDbContext;
you can read again example https://medium.com/swlh/building-a-nice-multi-layer-net-core-3-api-c68a9ef16368

2020-06-17 16:12 UTC, horba commented on server/WebAPI/Controllers/UserController.cs
> +                return Ok(user);
do you return user with password?? it is not okay, actually you don't need to send registred user at all, just success result

2020-06-17 16:12 UTC, horba commented on server/WebAPI/Controllers/UserController.cs
> +            User user = await dbContext.Users.FirstOrDefaultAsync(x => x.Email == value.Email);
it is business logic
it should be places in UserService
```
IUserService 
{
  bool IsUserExist(User user);
  void CreateUser(User user);
}
```

2020-06-17 16:39 UTC, IgorNazaryok commented on front/src/components/RegistrationUser/RegistrationUser.component.css
> +}
done

2020-06-17 16:43 UTC, IgorNazaryok commented on front/src/element-variables.scss
> +$--color-text-primary:  #000000 !default;
By default, the theme was set to $--color-text-primary: red. When setting up the theme, this did not appear.  When creating a modal window, I revealed a discrepancy in the topic. Corrected the color.

2020-06-17 17:27 UTC, IgorNazaryok commented on front/src/components/index.js
> +export { default as FfRegistrationUser } from './RegistrationUser/RegistrationUser.component.vue';
done

2020-06-17 17:32 UTC, IgorNazaryok commented on front/src/components/RegistrationUser/RegistrationUser.component.html
> +        <el-form-item class="inp-login" prop="userName">
done

2020-06-18 19:47 UTC, IgorNazaryok commented on front/src/components/index.js
> +export { default as FfRegistrationUser } from './RegistrationUser/RegistrationUser.component.vue';
done

2020-06-18 19:47 UTC, IgorNazaryok commented on front/src/components/RegistrationUser/RegistrationUser.component.css
> +}
done

2020-06-18 19:48 UTC, IgorNazaryok commented on front/src/components/RegistrationUser/RegistrationUser.component.html
> +        <el-form-item class="inp-login" prop="userName">
done

2020-06-18 19:59 UTC, IgorNazaryok commented on front/src/components/RegistrationUser/RegistrationUser.component.html
> +    <el-button class="second-color" @click="ShowModalWindow(true)">ВОЙТИ</el-button>
done. I chose "regisrationDialogVisible"

2020-06-18 20:05 UTC, IgorNazaryok commented on front/src/components/RegistrationUser/RegistrationUser.component.css
> +  color: #EE4444;
please clarify

2020-06-18 20:10 UTC, IgorNazaryok commented on front/src/components/RegistrationUser/RegistrationUser.component.css
> +  line-height: 2.0;
change to 
div {
}

2020-06-18 20:12 UTC, IgorNazaryok commented on front/src/components/RegistrationUser/RegistrationUser.component.html
> +    :show-close="false"
not suitable for style

2020-06-18 20:28 UTC, IgorNazaryok commented on front/src/components/RegistrationUser/RegistrationUser.component.html
> +                  @input="SetEmailExistFalse()"
removed

2020-06-18 20:31 UTC, IgorNazaryok commented on front/src/components/RegistrationUser/RegistrationUser.component.html
> +                  @input="SetEmailExistFalse()"
proper name "isEmailExist"?

2020-06-18 20:42 UTC, IgorNazaryok commented on front/src/components/RegistrationUser/RegistrationUser.component.html
> +            :disabled='isButton'
replaced "isFormFilled"

2020-06-18 20:43 UTC, IgorNazaryok commented on front/src/components/RegistrationUser/RegistrationUser.component.html
> +      :visible.sync="isRegistrationDone"
not relevant

2020-06-18 20:46 UTC, IgorNazaryok commented on front/src/components/RegistrationUser/RegistrationUser.component.html
> +    <div class="account-create">
removed

2020-06-18 20:48 UTC, IgorNazaryok commented on front/src/components/RegistrationUser/RegistrationUser.component.js
> +    ClouseWindowRegDone () {
done

2020-06-18 20:49 UTC, IgorNazaryok commented on front/src/components/RegistrationUser/RegistrationUser.component.js
> +      this.isEmailExist = false;
removed

2020-06-18 20:49 UTC, IgorNazaryok commented on front/src/components/RegistrationUser/RegistrationUser.component.vue
> +<style scoped src="./RegistrationUser.component.css"></style>
done

2020-06-18 20:50 UTC, IgorNazaryok commented on front/src/layouts/menu/menu.layout.css
> +.buttonEnter{
enter-button { }

2020-06-18 20:59 UTC, IgorNazaryok commented on front/src/layouts/menu/menu.layout.html
> +  </div>
<div class="actions">    
    <el-button icon="el-icon-search" class="second-color"></el-button>
    <ff-registration-dialog class="enter-button"/>
  </div>

2020-06-18 21:00 UTC, IgorNazaryok commented on front/src/layouts/menu/menu.layout.html
> +  </div>
<div class="actions">    
    <el-button icon="el-icon-search" class="second-color"></el-button>
    <ff-registration-dialog class="enter-button"/>
  </div>

2020-06-18 21:01 UTC, IgorNazaryok commented on front/src/layouts/menu/menu.layout.html
> +  </div>
removed
<div class="actions">    
    <el-button icon="el-icon-search" class="second-color"></el-button>
    <ff-registration-dialog class="enter-button"/>
  </div>

2020-06-18 21:03 UTC, IgorNazaryok commented on front/src/components/RegistrationUser/RegistrationUser.component.html
> +    :visible.sync="isRegistration"
done

2020-06-27 19:25 UTC, closed without merging

2020-06-27 20:05 UTC, horba reviewed
add translations for static text in ui

2020-06-27 20:05 UTC, horba commented on front/src/components/registration/registration-confirmation/registrationСonfirmation.component.html
> +      <p>Вперед за просмотрами, оценками и комментариями!</p>
add translations, please